### ISSUE TITLE
Are floating point values in JSON text columns problematic?

### ISSUE THREAD

**Issue by asutula** [tablelandnetwork/docs#52] opened 2022-12-09 21:42 UTC
The below is taken from a Discord thread:

@asutula: Did we evaluate the consequences of storing floating point values in text columns of json data? I think it would be ok since the value is handled as and stored as a string on the way in, and could maybe be a problem for read queries where you use a function like json_extract() where the docs explain:

> If only a single path P1 is provided, then the SQL datatype of the result is NULL for a JSON null, INTEGER or REAL for a JSON numeric value...

So if we really must stick to our rule that read query results must be deterministic, does this present a problem?

@brunocalza: interesting. gotta investigate that a bit more. but tbh it's getting hard to be very strict with that rule. there are already some scenarios where we cannot guarantee a deterministic result. for example, ORDER BY is one of them. when you sort by a column that is not able to break ties you can have problems, 

so let's see how that goes

@jsign: mmm i think that JSON situation might be a problem for the new INSERT with SELECT statements. in that case, feels we should block -> in those SELECTS maybe.
or even in simple UPDATEs, if an UPDATE has UPDATE .... WHERE foo->imafloat  :/
so maybe -> should be blocked in all write-queries.
just sharing first thoughts here. agree on thinking of it

**Comment by brunocalza** [comment] 2022-12-26 20:02
Did some tests and from the `INSERT` perspective it seems safe:

```
CREATE TABLE a (a int) STRICT;
INSERT INTO a VALUES ( '{"a":2.1}' ->> '$.a');
```

In `strict` mode, it throws an error:  `cannot store REAL value in INT column a.a`. Since we don't allow `ANY` and `REAL` types in columns, we should be safe. By that I mean, we would never store a `REAL` number that was extracted from a `JSON` because `SQLite` would always throw an error.

For the`UPDATE` case (and also `DELETE`) I'm not seeing good options. One option is to drop support for `json_extract` and `->>` on `WHERE` clauses, which seems very unfortunate. This would limit a lot of use cases that are really on JSON for unstructured data. 

Another option would be to avoid JSONs with FLOAT numbers inside a SQL statement. That would mean `foo->>imafloat` would never result in a REAL because we would never have stored a float number inside the JSON in the first place. Doing that check would be pretty ugly. 

cc @jsign

**Comment by jsign** [comment] 2022-12-26 20:42
> Did some tests and from the `INSERT` perspective it seems safe:
> 
> ```
> CREATE TABLE a (a int) STRICT;
> INSERT INTO a VALUES ( '{"a":2.1}' ->> '$.a');
> ```
> 
> In `strict` mode, it throws an error: `cannot store REAL value in INT column a.a`. Since we don't allow `ANY` and `REAL` types in columns, we should be safe. By that I mean, we would never store a `REAL` number that was extracted from a `JSON` because `SQLite` would always throw an error.

I was suspecting something, and I confirmed we'd still have a problem.
This works today: `INSERT INTO foo VALUES ( cast('{"a":2.1}' ->> '$.a' as INTEGER));`

Actually, this `CAST(...)` situation would be a problem from any cause that can return a REAL (`->` or `->>` probably is the only known case we know today).

> 
> For the`UPDATE` case (and also `DELETE`) I'm not seeing good options. One option is to drop support for `json_extract` and `->>` on `WHERE` clauses, which seems very unfortunate. This would limit a lot of use cases that rely on JSON for unstructured data.
> 
> Another option would be to avoid JSONs with FLOAT numbers inside a SQL statement. That would mean `foo->>imafloat` would never result in a REAL because we would never have stored a float number inside the JSON in the first place. Doing that check would be pretty ugly. Another way of looking at it is that we'd only support JSON with integer values.

Yeah, the problem here is that we'd have to detect any INSERT or UPDATE statement that is doing any `TEXT` column targeting, try to parse that value as JSON (even if that `TEXT` was never meant to be a JSON value), and walk all the JSON to see if any field can be interpreted as a REAL. Sounds very ugly for sure.

**Comment by dtbuchholz** [comment] 2023-03-27 17:43
@brunocalza @asutula do you know if this was resolved? (moving things to Linear so cleanup up issues and want to know if i i should migrate)

**Comment by asutula** [comment] 2023-03-31 15:43
I don't think it was, but want to double check with @brunocalza. In general, seems like we need to come up with a good strategy for when/where we need determinism. Maybe that would be the issue to create in Linear.

**Comment by brunocalza** [comment] 2023-03-31 15:53
This was not resolved. And TBH not sure how to move forward with this. I think ideally our JSON implementation shouldn't support the float. But we're relying on SQLite's JSON implementation. We have two options:
- Do what ignacio suggested
> try to parse that value as JSON (even if that TEXT was never meant to be a JSON value), and walk all the JSON to see if any field can be interpreted as a REAL. Sounds very ugly for sure.
- Tweak SQLite's JSON implementation. This is not hard but means maintaining a fork of https://github.com/mattn/go-sqlite3 😅

**Comment by dtbuchholz** [comment] 2023-03-31 17:36
@asutula @brunocalza sounds like this is worth keeping open but closing in the `docs` repo and move it to the parser or validator repo? just lmk where to put it

**Comment by brunocalza** [comment] 2023-04-03 14:53
@dtbuchholz You can put it in the validator repo for now

**Closed** 2023-04-03 22:14 UTC
